### ISSUE TITLE
Is frida-clr only usable from Windows or can it be used from mono too?

### ISSUE THREAD

**Issue by 7sharp9** [frida/frida-clr#3]

**Comment by oleavr** [comment]
It's written in Managed C++, which I don't think is supported by Mono. I did it quickly because it seemed easy and also gave me only a single file to deploy. Writing a PInvoke-based binding would be great if anyone's interested in helping out with that.

**Comment by 7sharp9** [comment]
I'll see if I can give the pinvoke binding a go, my use case is using fro a repl oriented clr language like F#.

**Comment by 7sharp9** [comment]
@oleavr I got a little lost in the build system...
What `DllImport` would I be binding against?  `libfrida-agent.dylib`, `libfrida-loader.dylib`?   I noticed that the python build was using `_frida.so`.

**Comment by oleavr** [comment]
@7sharp9 That would be awesome!  I'm afraid you'll have to add a build target to `frida-clr` so it packages up the APIs that you need into a `.dylib` that can be P/Invoked. The reason is that frida-core only provides `libfrida-core.a`, which is a static library intended for linking into bindings, and the symbols of a couple of Frida's internal dependencies (like libglib-2.0.a) should not leak out of the binding, as it will cause conflicts with apps that use a system version of those dependencies (e.g. GTK+-based apps implicitly depending on GLib). Longer term frida-core should probably also provide a .dylib with symbols properly mangled, but for now this is left up to the bindings, as they tend to have different requirements.

As a starting point you could copy the build-system from frida-python, and just export `^frida*`, and create a wrapper C function (or some linker script magic) to expose any GLib APIs prefixed with `frida_` or similar. If you're using the blocking API, like frida-python is (method names ending in `_sync`), you should only need to expose `g_object_unref` beside `frida*` (just create a wrapper function to avoid symbol conflicts).

**Comment by 7sharp9** [comment]
@oleavr Thanks!  Im not much of a c guy but Ill see if I can muddle through the python binding and see what I can do...

**Comment by oleavr** [comment]
No worries; feel free to poke me if anything's unclear!
